Parallel webpacks
mediamonks/display-dev-server pull request #84
Opened 2023-10-19 13:15 UTC by mm-vasyl

This PR provides speed enhancements from and resolves #83.
To use new features just use `-p` flag in display-dev-server. (`dds -m development -p`)
You can specify the number of cores to use with `-p [int]`. (`dds -m production -p 2`) (try not to blow your PC).
The default is 4.

Works for both build and dev.

The only issue is that devtools can't be used on dev because threads are running a few different express apps on a few ports (it's impossible to pass the same app instance to the thread so that's the only way to speed the process). But if you really want to use devtools in parallel you can simply disable CORS security in your browser. No other programmatic solution here.

How to disable CORS on Windows (use it wisely):
`Win + R`
`chrome.exe --user-data-dir="C://Chrome dev session" --disable-web-security`
Mac:
`open -n -a /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --args --user-data-dir="/tmp/chrome_dev_test" --disable-web-security`

More about CORS here: [MDN](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy)

Quick testing results with 4 threads:
- build: 135 banners with compression 110s -> 60s
- dev: 135 banners 90s -> 42s

2023-10-24 06:33 UTC, xaviergdiez84 approved these changes
Works like a charm, 135 banners in 40s

2023-10-26 12:12 UTC, mm-paulie approved these changes
Tested it with a big project of 300 banners and it works really well. 
Small comments: Maybe we should add a warning when running the command that gsdevtools does not work and when building/running dev, something like "this might take a while be patient" instead of "Server running. Please go to http://localhost:8000"  since this will only be available when everything is done building.

2023-11-06 10:28 UTC, mm-paulie requested changes
Perfect this amend! Could we also add the "Server http://localhost:8000 will open automatically once everything is ready. This might take a while." to the original npm run dev command?

2023-11-06 10:37 UTC, mm-paulie approved these changes

2023-11-16 12:33 UTC, merged